# Generated by Django 2.2.3 on 2019-07-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='id',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
