# Generated by Django 2.2.3 on 2019-07-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='real_stress_level',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
    ]
