# Generated by Django 2.2.3 on 2019-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0002_auto_20190711_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='real_stress_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
