# Generated by Django 2.2.3 on 2019-07-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0002_auto_20190710_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intervention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainModule.Intervention'),
        ),
    ]
