# Generated by Django 2.2.3 on 2019-07-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0003_event_intervention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_reminder',
            new_name='event_reminder_timedelta',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='stress_cause',
            new_name='expected_stress_cause',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='stress_level',
            new_name='expected_stress_level',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='stress_type',
            new_name='expected_stress_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='intervention_reminder',
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeat_id',
        ),
        migrations.AddField(
            model_name='event',
            name='intervention_reminder_timedelta',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='event',
            name='repetition_id',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='real_stress_level',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_till',
            field=models.BigIntegerField(default=-1),
        ),
    ]
