# Generated by Django 2.2.3 on 2019-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0003_auto_20190711_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_modified_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
