# Generated by Django 2.2.3 on 2019-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0004_event_last_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_modified_time',
            field=models.BigIntegerField(),
        ),
    ]
