# Generated by Django 2.2.3 on 2019-07-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0004_auto_20190710_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='id',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainModule.Event'),
        ),
    ]
