# Generated by Django 2.2.3 on 2019-07-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0005_auto_20190712_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='last_modified_time',
            new_name='intervention_last_picked_time',
        ),
    ]
