# Generated by Django 2.2.3 on 2019-07-15 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0006_auto_20190712_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='end_ts',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='start_ts',
        ),
        migrations.CreateModel(
            name='AppUsageStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_used', models.BigIntegerField()),
                ('total_time_in_foreground', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'last_time_used', 'total_time_in_foreground')},
            },
        ),
    ]
