# Generated by Django 2.2.3 on 2019-07-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0007_auto_20190715_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusagestats',
            old_name='last_time_used',
            new_name='end_timestamp',
        ),
        migrations.RenameField(
            model_name='appusagestats',
            old_name='total_time_in_foreground',
            new_name='start_timestamp',
        ),
        migrations.AddField(
            model_name='appusagestats',
            name='number_of_launches',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appusagestats',
            unique_together={('user', 'start_timestamp', 'end_timestamp')},
        ),
    ]
