# Generated by Django 2.2.3 on 2019-07-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0008_auto_20190715_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusagestats',
            name='number_of_launches',
            field=models.IntegerField(default=1),
        ),
    ]
