# Generated by Django 2.2.3 on 2019-07-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0009_auto_20190715_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appusagestats',
            unique_together={('user', 'start_timestamp')},
        ),
    ]
