# Generated by Django 2.2.3 on 2019-07-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0010_auto_20190715_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusagestats',
            name='number_of_launches',
        ),
    ]
