# Generated by Django 2.2.3 on 2019-07-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0011_remove_appusagestats_number_of_launches'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusagestats',
            name='total_time_in_foreground',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
