# Generated by Django 2.2.3 on 2019-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0012_appusagestats_total_time_in_foreground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expected_stress_level',
            field=models.SmallIntegerField(),
        ),
    ]
