# Generated by Django 2.2.3 on 2019-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModule', '0014_auto_20190715_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='real_stress_level',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
